GlobalParameters:
  MinimumRequiredVersion: 4.2.0
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 0
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False
  SleepPercent: 25
  DataInitTypeBeta : 0
  SolutionSelectionAlg: 1
  PrintWinnersOnly: 1

BenchmarkProblems:
  ########################################
  # TN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True
    
  ########################################
  # Explore large number of ~10K solutions
  ########################################
    - # Benchmark Group
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - FractionalLoad: [1]
        - PrefetchGlobalRead: [ False, True ]
        - PrefetchLocalRead: [ True]
        - ThreadTile:
          - [ 4, 4 ]
          - [ 4, 8 ]
          - [ 8, 4 ]
          - [ 8, 8 ]
          - [ 10, 6 ]
          - [ 6, 10 ]
        - WorkGroup:
          #- [ 16, 8, 2 ]
          #- [ 16, 4, 4 ]
          - [ 16,  8, 1 ]
          - [ 8, 32, 1 ]
          - [ 16, 16, 1 ]
          - [ 32,  8, 1 ]
        - GlobalSplitU: [1,3,5]
        - WorkGroupMapping: [1,8,64]
        - DepthU: [ 8,16,32 ]
        - VectorWidth: [2,4]
        - GlobalReadVectorWidth: [1,4]
        - LdsPadA: [0, -1 ]
        - LdsPadB: [0, -1 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [[1],[256,256,256,1024],[1],[1024,1024,1024,4096]]
          - Range: [[1],[200],[1],[1024,1024,1024,4096]]
          - Range: [[1024,1024,1024,4096],[256,256,256,1024],[1],[32,32,32,128]]
          - Range: [[1024,1024,1024,4096],[256,256,256,1024],[1],[256]]
          - Range: [[1024,1024,1024,4096],[200],[1],[32,32,32,128]]
          - Range: [[1024,1024,1024,4096],[200],[1],[256]]
          - Range: [[1024,1024,1024,4096],[256,256,256,1024],[1],[2080,2080,2080,8320]]
          - Range: [[1024,1024,1024,4096],[256,256,256,1024],[1],[16640]]
          - Range: [[1024,1024,1024,4096],[200],[1],[2080,2080,2080,8320]]
          - Range: [[1024,1024,1024,4096],[200],[1],[16640]]
          - Range: [[1024,1024,1024,4096],[256,256,256,1024],[1],[128,128,0,2048]]
          - Range: [[1024,1024,1024,4096],[200],[1],[128,128,0,2048]]
          - Range: [[1024,1024,1024,4096],[256,256,256,1024],[1],[256,256,0,4096]]
          - Range: [[1024,1024,1024,4096],[200],[1],[256,256,0,4096]]
          - Range: [[1024,1024,1024,4096],[256,256,256,1024],[1],[512,512,0,8192]]
          - Range: [[1024,1024,1024,4096],[200],[1],[512,512,0,8192]]
          - Range: [[1024,1024,1024,4096],[256,256,256,1024],[1],[1024,1024,0,16384]]
          - Range: [[1024,1024,1024,4096],[200],[1],[1024,1024,0,16384]]
          - Range: [[32,32,32,128],[256,256,256,1024],[1],[512,512,512,2048]]
          - Range: [[256],[256,256,256,1024],[1],[512,512,512,2048]]
          - Range: [[32,32,32,128],[200],[1],[512,512,512,2048]]
          - Range: [[256],[200],[1],[512,512,512,2048]]
          - Range: [[512,512,512,2048],[256,256,256,1024],[1],[512,256,0,3072]]
          - Range: [[512,512,512,2048],[256,256,256,1024],[1],[3200]]
          - Range: [[512,512,512,2048],[200],[1],[512,256,0,3072]]
          - Range: [[512,512,512,2048],[200],[1],[3200]]

LibraryLogic:
    ScheduleName: "vega20"
    DeviceNames: ["Device 66a0", "Device 66a1", "Device 66a7"]
    ArchitectureName: "gfx906"

#    ScheduleName: "vega10"
#    DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860", "Device 6861", "Vega 10 XTX [Radeon Vega Frontier Edition]", "Vega [Radeon RX Vega]","Vega 10 XL/XT [Radeon RX Vega 56/64]"]
#    ArchitectureName: "gfx900"

#   ScheduleName: "mi25"
#   DeviceNames: ["Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "r9nano"
#   DeviceNames: ["Device 7300"]
#   ArchitectureName: "gfx803"

#   ScheduleName: "hip"
#   DeviceNames: ["Device 0000"]
#   ArchitectureName: "fallback"

LibraryClient:
