GlobalParameters:
  MinimumRequiredVersion: 4.14.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 16384
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False
  SleepPercent: 200
  PrintSolutionRejectionReason: True
  DataInitTypeA: 3
  DataInitTypeB: 3
  #DataInitTypeC: 0
  #DataInitTypeD: 0
  DataInitTypeBeta: 2
  DataInitTypeAlpha: 2
  PrintTensorA: 0
  PrintTensorB: 0
  PrintTensorD: 0
  NewClient: 0

BenchmarkProblems:
  ########################################
  # TN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: B
      DestDataType: B
      ComputeDataType: s
      HighPrecisionAccumulate: True
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        #- LoopTail: [True]
        - PrefetchLocalRead: [True]
        - AssertSummationElementMultiple: [2]
        - AssertFree0ElementMultiple: [2]
      ForkParameters:
        - MatrixInstruction:
          - [32, 32, 2, 2]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 1, 32 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
          - [ 64, 4, 1 ]
        - WorkGroupMapping: [8]
        - GlobalSplitU: [1]
        - DepthU: [8,16,32]
        - VectorWidth: [2]
        - GlobalReadVectorWidth: [-1,2,4]
        - SuppressNoLoadLoop: [True,False]
        - OptNoLoadLoop: [0,1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 10240, 8976, 1, 256, 10240, 10240, 256, 256 ]
          - Exact: [ 1024, 1600, 1, 1024, 1024, 1024, 1024, 1024 ]
          - Exact: [ 1024, 1600, 1, 560, 1024, 1024, 560, 560 ]
          - Exact: [ 1024, 200, 1, 560, 1024, 1024, 560, 560 ]
          - Exact: [ 1024, 512, 1, 1024, 1024, 1024, 1024, 1024 ]
          - Exact: [ 1024, 512, 1, 1600, 1024, 1024, 1600, 1600 ]
          - Exact: [ 10496, 8976, 1, 256, 10496, 10496, 256, 256 ]
          - Exact: [ 11264, 8976, 1, 256, 11264, 11264, 256, 256 ]
          - Exact: [ 11776, 8976, 1, 256, 11776, 11776, 256, 256 ]
          - Exact: [ 12544, 8976, 1, 256, 12544, 12544, 256, 256 ]
          - Exact: [ 1280, 8976, 1, 256, 1280, 1280, 256, 256 ]
          - Exact: [ 13312, 8976, 1, 256, 13312, 13312, 256, 256 ]
          - Exact: [ 13568, 8976, 1, 256, 13568, 13568, 256, 256 ]
          - Exact: [ 13824, 8976, 1, 256, 13824, 13824, 256, 256 ]
          - Exact: [ 15104, 8976, 1, 256, 15104, 15104, 256, 256 ]
          - Exact: [ 15360, 8976, 1, 256, 15360, 15360, 256, 256 ]
          - Exact: [ 15872, 8976, 1, 256, 15872, 15872, 256, 256 ]
          - Exact: [ 1600, 1, 1, 1024, 1600, 1600, 1024, 1024 ]
          - Exact: [ 16128, 8976, 1, 256, 16128, 16128, 256, 256 ]
          - Exact: [ 17152, 8976, 1, 256, 17152, 17152, 256, 256 ]
          - Exact: [ 1792, 8976, 1, 256, 1792, 1792, 256, 256 ]
          - Exact: [ 18176, 8976, 1, 256, 18176, 18176, 256, 256 ]
          - Exact: [ 18688, 8976, 1, 256, 18688, 18688, 256, 256 ]
          - Exact: [ 18944, 8976, 1, 256, 18944, 18944, 256, 256 ]
          - Exact: [ 19712, 8976, 1, 256, 19712, 19712, 256, 256 ]
          - Exact: [ 19968, 8976, 1, 256, 19968, 19968, 256, 256 ]
          - Exact: [ 200, 1, 1, 1024, 200, 200, 1024, 1024 ]
          - Exact: [ 20480, 8976, 1, 256, 20480, 20480, 256, 256 ]
          - Exact: [ 2048, 114, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 114, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 1536, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 1536, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 215, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 215, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 256, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 256, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 512, 1, 100, 2048, 2048, 100, 100 ]
          - Exact: [ 2048, 512, 1, 2048, 2048, 2048, 2048, 2048 ]
          - Exact: [ 2048, 512, 1, 67, 2048, 2048, 67, 67 ]
          - Exact: [ 2048, 512, 1, 74, 2048, 2048, 74, 74 ]
          - Exact: [ 2048, 684, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 684, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 8976, 1, 256, 2048, 2048, 256, 256 ]
          - Exact: [ 20992, 8976, 1, 256, 20992, 20992, 256, 256 ]
          - Exact: [ 21248, 8976, 1, 256, 21248, 21248, 256, 256 ]
          - Exact: [ 2304, 8976, 1, 256, 2304, 2304, 256, 256 ]
          - Exact: [ 23552, 8976, 1, 256, 23552, 23552, 256, 256 ]
          - Exact: [ 2560, 8976, 1, 256, 2560, 2560, 256, 256 ]
          - Exact: [ 256, 10496, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 11264, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 11520, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 11776, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 12544, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 1280, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 13312, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 14336, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 14592, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 14848, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 15104, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 1536, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 16128, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 18176, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 18944, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 19200, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 20480, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 20992, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 21248, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 21504, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 22016, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 22344, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 2304, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 23296, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 23552, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 2560, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 2816, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 31488, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 3328, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 33536, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 3584, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 44505, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 4608, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 4864, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 5376, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 5888, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 6144, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 6400, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 6656, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 684, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 7168, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 7424, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 7936, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 8192, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 8448, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 8960, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 9984, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 2816, 8976, 1, 256, 2816, 2816, 256, 256 ]
          - Exact: [ 28672, 8976, 1, 256, 28672, 28672, 256, 256 ]
          - Exact: [ 3072, 8976, 1, 256, 3072, 3072, 256, 256 ]
          - Exact: [ 31488, 8976, 1, 256, 31488, 31488, 256, 256 ]
          - Exact: [ 32, 1600, 1, 512, 32, 32, 512, 512 ]
          - Exact: [ 3328, 8976, 1, 256, 3328, 3328, 256, 256 ]
          - Exact: [ 33536, 8976, 1, 256, 33536, 33536, 256, 256 ]
          - Exact: [ 3840, 8976, 1, 256, 3840, 3840, 256, 256 ]
          - Exact: [ 4096, 8976, 1, 256, 4096, 4096, 256, 256 ]
          - Exact: [ 4352, 8976, 1, 256, 4352, 4352, 256, 256 ]
          - Exact: [ 44505, 8976, 1, 256, 44505, 44505, 256, 256 ]
          - Exact: [ 4608, 8976, 1, 256, 4608, 4608, 256, 256 ]
          - Exact: [ 4864, 8976, 1, 256, 4864, 4864, 256, 256 ]
          - Exact: [ 5120, 8976, 1, 256, 5120, 5120, 256, 256 ]
          - Exact: [ 512, 1, 1, 2048, 512, 512, 2048, 2048 ]
          - Exact: [ 512, 1600, 1, 512, 512, 512, 512, 512 ]
          - Exact: [ 5376, 8976, 1, 256, 5376, 5376, 256, 256 ]
          - Exact: [ 5632, 8976, 1, 256, 5632, 5632, 256, 256 ]
          - Exact: [ 5888, 8976, 1, 256, 5888, 5888, 256, 256 ]
          - Exact: [ 6144, 8976, 1, 256, 6144, 6144, 256, 256 ]
          - Exact: [ 6400, 8976, 1, 256, 6400, 6400, 256, 256 ]
          - Exact: [ 64, 512, 1, 1024, 64, 64, 1024, 1024 ]
          - Exact: [ 684, 8976, 1, 256, 684, 684, 256, 256 ]
          - Exact: [ 7168, 8976, 1, 256, 7168, 7168, 256, 256 ]
          - Exact: [ 7936, 8976, 1, 256, 7936, 7936, 256, 256 ]
          - Exact: [ 8192, 8976, 1, 256, 8192, 8192, 256, 256 ]
          - Exact: [ 8448, 8976, 1, 256, 8448, 8448, 256, 256 ]
          - Exact: [ 8960, 8976, 1, 256, 8960, 8960, 256, 256 ]
          - Exact: [ 9472, 8976, 1, 256, 9472, 9472, 256, 256 ]
          - Exact: [ 9728, 8976, 1, 256, 9728, 9728, 256, 256 ]
          - Exact: [ 9984, 8976, 1, 256, 9984, 9984, 256, 256 ]
          - Exact: [ 33, 33, 1600, 32, 33, 33, 32, 32 ]
          - Exact: [ 3, 3, 512, 64, 3, 3, 64, 64 ]
          - Exact: [ 5, 5, 512, 64, 5, 5, 64, 64 ]
          - Exact: [ 9, 9, 512, 64, 9, 9, 64, 64 ]

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        #- LoopTail: [True]
        - PrefetchLocalRead: [True]
        - AssertSummationElementMultiple: [2]
        - AssertFree0ElementMultiple: [2]
      ForkParameters:
        - MatrixInstruction:
          - [32, 32, 2, 2]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 2, 32 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
        - WorkGroupMapping: [8]
        - GlobalSplitU: [1]
        - DepthU: [8,16]
        - VectorWidth: [2]
        - GlobalReadVectorWidth: [-1,2,4]
        - SuppressNoLoadLoop: [True,False]
        - OptNoLoadLoop: [0,1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 10240, 8976, 1, 256, 10240, 10240, 256, 256 ]
          - Exact: [ 1024, 1600, 1, 1024, 1024, 1024, 1024, 1024 ]
          - Exact: [ 1024, 1600, 1, 560, 1024, 1024, 560, 560 ]
          - Exact: [ 1024, 200, 1, 560, 1024, 1024, 560, 560 ]
          - Exact: [ 1024, 512, 1, 1024, 1024, 1024, 1024, 1024 ]
          - Exact: [ 1024, 512, 1, 1600, 1024, 1024, 1600, 1600 ]
          - Exact: [ 10496, 8976, 1, 256, 10496, 10496, 256, 256 ]
          - Exact: [ 11264, 8976, 1, 256, 11264, 11264, 256, 256 ]
          - Exact: [ 11776, 8976, 1, 256, 11776, 11776, 256, 256 ]
          - Exact: [ 12544, 8976, 1, 256, 12544, 12544, 256, 256 ]
          - Exact: [ 1280, 8976, 1, 256, 1280, 1280, 256, 256 ]
          - Exact: [ 13312, 8976, 1, 256, 13312, 13312, 256, 256 ]
          - Exact: [ 13568, 8976, 1, 256, 13568, 13568, 256, 256 ]
          - Exact: [ 13824, 8976, 1, 256, 13824, 13824, 256, 256 ]
          - Exact: [ 15104, 8976, 1, 256, 15104, 15104, 256, 256 ]
          - Exact: [ 15360, 8976, 1, 256, 15360, 15360, 256, 256 ]
          - Exact: [ 15872, 8976, 1, 256, 15872, 15872, 256, 256 ]
          - Exact: [ 1600, 1, 1, 1024, 1600, 1600, 1024, 1024 ]
          - Exact: [ 16128, 8976, 1, 256, 16128, 16128, 256, 256 ]
          - Exact: [ 17152, 8976, 1, 256, 17152, 17152, 256, 256 ]
          - Exact: [ 1792, 8976, 1, 256, 1792, 1792, 256, 256 ]
          - Exact: [ 18176, 8976, 1, 256, 18176, 18176, 256, 256 ]
          - Exact: [ 18688, 8976, 1, 256, 18688, 18688, 256, 256 ]
          - Exact: [ 18944, 8976, 1, 256, 18944, 18944, 256, 256 ]
          - Exact: [ 19712, 8976, 1, 256, 19712, 19712, 256, 256 ]
          - Exact: [ 19968, 8976, 1, 256, 19968, 19968, 256, 256 ]
          - Exact: [ 200, 1, 1, 1024, 200, 200, 1024, 1024 ]
          - Exact: [ 20480, 8976, 1, 256, 20480, 20480, 256, 256 ]
          - Exact: [ 2048, 114, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 114, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 1536, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 1536, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 215, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 215, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 256, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 256, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 512, 1, 100, 2048, 2048, 100, 100 ]
          - Exact: [ 2048, 512, 1, 2048, 2048, 2048, 2048, 2048 ]
          - Exact: [ 2048, 512, 1, 67, 2048, 2048, 67, 67 ]
          - Exact: [ 2048, 512, 1, 74, 2048, 2048, 74, 74 ]
          - Exact: [ 2048, 684, 1, 512, 2048, 2048, 512, 512 ]
          - Exact: [ 2048, 684, 1, 768, 2048, 2048, 768, 768 ]
          - Exact: [ 2048, 8976, 1, 256, 2048, 2048, 256, 256 ]
          - Exact: [ 20992, 8976, 1, 256, 20992, 20992, 256, 256 ]
          - Exact: [ 21248, 8976, 1, 256, 21248, 21248, 256, 256 ]
          - Exact: [ 2304, 8976, 1, 256, 2304, 2304, 256, 256 ]
          - Exact: [ 23552, 8976, 1, 256, 23552, 23552, 256, 256 ]
          - Exact: [ 2560, 8976, 1, 256, 2560, 2560, 256, 256 ]
          - Exact: [ 256, 10496, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 11264, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 11520, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 11776, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 12544, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 1280, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 13312, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 14336, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 14592, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 14848, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 15104, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 1536, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 16128, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 18176, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 18944, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 19200, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 20480, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 20992, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 21248, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 21504, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 22016, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 22344, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 2304, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 23296, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 23552, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 2560, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 2816, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 31488, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 3328, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 33536, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 3584, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 44505, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 4608, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 4864, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 5376, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 5888, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 6144, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 6400, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 6656, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 684, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 7168, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 7424, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 7936, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 8192, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 8448, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 8960, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 256, 9984, 1, 1024, 256, 256, 1024, 1024 ]
          - Exact: [ 2816, 8976, 1, 256, 2816, 2816, 256, 256 ]
          - Exact: [ 28672, 8976, 1, 256, 28672, 28672, 256, 256 ]
          - Exact: [ 3072, 8976, 1, 256, 3072, 3072, 256, 256 ]
          - Exact: [ 31488, 8976, 1, 256, 31488, 31488, 256, 256 ]
          - Exact: [ 32, 1600, 1, 512, 32, 32, 512, 512 ]
          - Exact: [ 3328, 8976, 1, 256, 3328, 3328, 256, 256 ]
          - Exact: [ 33536, 8976, 1, 256, 33536, 33536, 256, 256 ]
          - Exact: [ 3840, 8976, 1, 256, 3840, 3840, 256, 256 ]
          - Exact: [ 4096, 8976, 1, 256, 4096, 4096, 256, 256 ]
          - Exact: [ 4352, 8976, 1, 256, 4352, 4352, 256, 256 ]
          - Exact: [ 44505, 8976, 1, 256, 44505, 44505, 256, 256 ]
          - Exact: [ 4608, 8976, 1, 256, 4608, 4608, 256, 256 ]
          - Exact: [ 4864, 8976, 1, 256, 4864, 4864, 256, 256 ]
          - Exact: [ 5120, 8976, 1, 256, 5120, 5120, 256, 256 ]
          - Exact: [ 512, 1, 1, 2048, 512, 512, 2048, 2048 ]
          - Exact: [ 512, 1600, 1, 512, 512, 512, 512, 512 ]
          - Exact: [ 5376, 8976, 1, 256, 5376, 5376, 256, 256 ]
          - Exact: [ 5632, 8976, 1, 256, 5632, 5632, 256, 256 ]
          - Exact: [ 5888, 8976, 1, 256, 5888, 5888, 256, 256 ]
          - Exact: [ 6144, 8976, 1, 256, 6144, 6144, 256, 256 ]
          - Exact: [ 6400, 8976, 1, 256, 6400, 6400, 256, 256 ]
          - Exact: [ 64, 512, 1, 1024, 64, 64, 1024, 1024 ]
          - Exact: [ 684, 8976, 1, 256, 684, 684, 256, 256 ]
          - Exact: [ 7168, 8976, 1, 256, 7168, 7168, 256, 256 ]
          - Exact: [ 7936, 8976, 1, 256, 7936, 7936, 256, 256 ]
          - Exact: [ 8192, 8976, 1, 256, 8192, 8192, 256, 256 ]
          - Exact: [ 8448, 8976, 1, 256, 8448, 8448, 256, 256 ]
          - Exact: [ 8960, 8976, 1, 256, 8960, 8960, 256, 256 ]
          - Exact: [ 9472, 8976, 1, 256, 9472, 9472, 256, 256 ]
          - Exact: [ 9728, 8976, 1, 256, 9728, 9728, 256, 256 ]
          - Exact: [ 9984, 8976, 1, 256, 9984, 9984, 256, 256 ]
          - Exact: [ 33, 33, 1600, 32, 33, 33, 32, 32 ]
          - Exact: [ 3, 3, 512, 64, 3, 3, 64, 64 ]
          - Exact: [ 5, 5, 512, 64, 5, 5, 64, 64 ]
          - Exact: [ 9, 9, 512, 64, 9, 9, 64, 64 ]

########################################
LibraryLogic:
    ScheduleName: "arcturus"
    DeviceNames: ["Device 7380", "Device 7388", "Device 738c", "Device 7390"]
    ArchitectureName: "gfx908"
