GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 2
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: True
  SleepPercent: 200

BenchmarkProblems:
  - # dgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 1536, 1536, 2, 1536 ]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - ThreadTile:
          - [ 4, 8 ]
          - [ 4, 4 ]
          - [ 2, 4 ]
        - WorkGroup:
          - [  4,  4, 16 ]
          - [  4,  8,  8 ]
          - [  8,  8,  4 ]
          - [  8, 16,  2 ]
          - [ 16, 16,  1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 2000], [32, 32, 32, 2000], [2], [1536] ]

  - # dgemm NT
    - # ProblemType:
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 1536, 1536, 2, 1536 ]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - ThreadTile:
          - [ 4, 8 ]
          - [ 4, 4 ]
          - [ 2, 4 ]
        - WorkGroup:
          - [  4,  4, 16 ]
          - [  4,  8,  8 ]
          - [  8,  8,  4 ]
          - [  8, 16,  2 ]
          - [ 16, 16,  1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 2000], [32, 32, 32, 2000], [2], [1536] ]

  - # dgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 1536, 1536, 2, 1536 ]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
      ForkParameters:
        - ThreadTile:
          - [ 4, 8 ]
          - [ 4, 4 ]
          - [ 2, 4 ]
        - WorkGroup:
          - [  4,  4, 16 ]
          - [  4,  8,  8 ]
          - [  8,  8,  4 ]
          - [  8, 16,  2 ]
          - [ 16, 16,  1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 2000], [32, 32, 32, 2000], [2], [1536] ]

  - # dgemm TT
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
        - WorkGroupMapping: [-1]
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 1536, 1536, 2, 1536 ]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
      ForkParameters:
        - ThreadTile:
          - [ 4, 8 ]
          - [ 4, 4 ]
          - [ 2, 4 ]
        - WorkGroup:
          - [  4,  4, 16 ]
          - [  4,  8,  8 ]
          - [  8,  8,  4 ]
          - [  8, 16,  2 ]
          - [ 16, 16,  1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 2000], [32, 32, 32, 2000], [2], [1536] ]

LibraryLogic:

LibraryClient:
