GlobalParameters:
  MinimumRequiredVersion: 4.3.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 2
  LibraryPrintDebug: False
  NumElementsToValidate: 256
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False
  SleepPercent: 0
  DataInitTypeBeta : 0
# PrintSolutionRejectionReason: True
# SolutionSelectionAlg: 1
# PrintWinnersOnly: 1
# ExitOnFails: 0

BenchmarkProblems:

  ########################################
  # TN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 8 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [1], [64] ]

    - # BenchmarkProblemSizeGroup - M,N < VW
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 4 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1], [1], [1], [64] ]
          - Range: [ [1], [64], [1], [64] ]
          - Range: [ [64], [1], [1], [64] ]

LibraryLogic:
    ScheduleName: "vega20"
    DeviceNames: ["Device 66a0", "Device 66a1", "Device 66a7"]
    ArchitectureName: "gfx906"

#   ScheduleName: "vega10"
#   DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860", "Device 6861", "Vega 10 XTX [Radeon Vega Frontier Edition]", "Vega [Radeon RX Vega]"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "mi25"
#   DeviceNames: ["Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "r9nano"
#   DeviceNames: ["Device 7300"]
#   ArchitectureName: "gfx803"

#   ScheduleName: "hip"
#   DeviceNames: ["Device 0000"]
#   ArchitectureName: "fallback"

LibraryClient:
