GlobalParameters:
  MinimumRequiredVersion: 4.14.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 16384
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False
  SleepPercent: 200
  PrintSolutionRejectionReason: True
  DataInitTypeA: 3
  DataInitTypeB: 3
  #DataInitTypeC: 0
  #DataInitTypeD: 0
  DataInitTypeBeta: 2
  DataInitTypeAlpha: 2
  PrintTensorA: 0
  PrintTensorB: 0
  PrintTensorD: 0
  NewClient: 0

BenchmarkProblems:
  ########################################
  # NN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        #- LoopTail: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [32, 32, 1, 2]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 1, 32 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
          - [ 64, 4, 1 ]
        - WorkGroupMapping: [8]
        - GlobalSplitU: [1]
        - DepthU: [8,16,32]
        - VectorWidth: [1]
        - GlobalReadVectorWidth: [-1,1,2,4]
        - SuppressNoLoadLoop: [True,False]
        - OptNoLoadLoop: [0,1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 100, 512, 1, 2048, 100, 100, 100, 2048 ]
          - Exact: [ 1024, 10240, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 10496, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 11008, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 11264, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 11520, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 1, 1, 1600, 1024, 1024, 1024, 1600 ]
          - Exact: [ 1024, 1, 1, 200, 1024, 1024, 1024, 200 ]
          - Exact: [ 1024, 12288, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 13312, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 13568, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 14336, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 14592, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 14848, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 15104, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 1600, 1, 1024, 1024, 1024, 1024, 1024 ]
          - Exact: [ 1024, 1600, 1, 1, 1024, 1024, 1024, 1 ]
          - Exact: [ 1024, 16128, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 17152, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 1792, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 18944, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 19712, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 19968, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 200, 1, 1, 1024, 1024, 1024, 1 ]
          - Exact: [ 1024, 20480, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 2048, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 20992, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 21504, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 22016, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 23552, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 2560, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 28672, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 3072, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 3328, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 33536, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 3840, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 40448, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 4096, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 4608, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 4864, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 5120, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 512, 1, 1024, 1024, 1024, 1024, 1024 ]
          - Exact: [ 1024, 512, 1, 1, 1024, 1024, 1024, 1 ]
          - Exact: [ 1024, 512, 1, 64, 1024, 1024, 1024, 64 ]
          - Exact: [ 1024, 5632, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 6144, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 6400, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 7168, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 7424, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 7680, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 7936, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 8192, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 8448, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 8704, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 8960, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 9728, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 9984, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1, 200, 1, 1, 1, 1, 1, 1 ]
          - Exact: [ 1, 512, 1, 1, 1, 1, 1, 1 ]
          - Exact: [ 1600, 512, 1, 1024, 1600, 1600, 1600, 1024 ]
          - Exact: [ 2048, 1024, 1, 1, 2048, 2048, 2048, 1 ]
          - Exact: [ 2048, 1024, 1, 256, 2048, 2048, 2048, 256 ]
          - Exact: [ 2048, 1, 1, 512, 2048, 2048, 2048, 512 ]
          - Exact: [ 2048, 512, 1, 1, 2048, 2048, 2048, 1 ]
          - Exact: [ 2048, 512, 1, 2048, 2048, 2048, 2048, 2048 ]
          - Exact: [ 256, 1024, 1, 1, 256, 256, 256, 1 ]
          - Exact: [ 256, 8976, 1, 10240, 256, 256, 256, 10240 ]
          - Exact: [ 256, 8976, 1, 10496, 256, 256, 256, 10496 ]
          - Exact: [ 256, 8976, 1, 11008, 256, 256, 256, 11008 ]
          - Exact: [ 256, 8976, 1, 11520, 256, 256, 256, 11520 ]
          - Exact: [ 256, 8976, 1, 12288, 256, 256, 256, 12288 ]
          - Exact: [ 256, 8976, 1, 14336, 256, 256, 256, 14336 ]
          - Exact: [ 256, 8976, 1, 14848, 256, 256, 256, 14848 ]
          - Exact: [ 256, 8976, 1, 15104, 256, 256, 256, 15104 ]
          - Exact: [ 256, 8976, 1, 1536, 256, 256, 256, 1536 ]
          - Exact: [ 256, 8976, 1, 15872, 256, 256, 256, 15872 ]
          - Exact: [ 256, 8976, 1, 17152, 256, 256, 256, 17152 ]
          - Exact: [ 256, 8976, 1, 19712, 256, 256, 256, 19712 ]
          - Exact: [ 256, 8976, 1, 19968, 256, 256, 256, 19968 ]
          - Exact: [ 256, 8976, 1, 20480, 256, 256, 256, 20480 ]
          - Exact: [ 256, 8976, 1, 2048, 256, 256, 256, 2048 ]
          - Exact: [ 256, 8976, 1, 20992, 256, 256, 256, 20992 ]
          - Exact: [ 256, 8976, 1, 22016, 256, 256, 256, 22016 ]
          - Exact: [ 256, 8976, 1, 2304, 256, 256, 256, 2304 ]
          - Exact: [ 256, 8976, 1, 2560, 256, 256, 256, 2560 ]
          - Exact: [ 256, 8976, 1, 26112, 256, 256, 256, 26112 ]
          - Exact: [ 256, 8976, 1, 2816, 256, 256, 256, 2816 ]
          - Exact: [ 256, 8976, 1, 3072, 256, 256, 256, 3072 ]
          - Exact: [ 256, 8976, 1, 33536, 256, 256, 256, 33536 ]
          - Exact: [ 256, 8976, 1, 4352, 256, 256, 256, 4352 ]
          - Exact: [ 256, 8976, 1, 44505, 256, 256, 256, 44505 ]
          - Exact: [ 256, 8976, 1, 4864, 256, 256, 256, 4864 ]
          - Exact: [ 256, 8976, 1, 5376, 256, 256, 256, 5376 ]
          - Exact: [ 256, 8976, 1, 5632, 256, 256, 256, 5632 ]
          - Exact: [ 256, 8976, 1, 5888, 256, 256, 256, 5888 ]
          - Exact: [ 256, 8976, 1, 6144, 256, 256, 256, 6144 ]
          - Exact: [ 256, 8976, 1, 6656, 256, 256, 256, 6656 ]
          - Exact: [ 256, 8976, 1, 7168, 256, 256, 256, 7168 ]
          - Exact: [ 256, 8976, 1, 7424, 256, 256, 256, 7424 ]
          - Exact: [ 256, 8976, 1, 8192, 256, 256, 256, 8192 ]
          - Exact: [ 256, 8976, 1, 8448, 256, 256, 256, 8448 ]
          - Exact: [ 256, 8976, 1, 8960, 256, 256, 256, 8960 ]
          - Exact: [ 256, 8976, 1, 9472, 256, 256, 256, 9472 ]
          - Exact: [ 256, 8976, 1, 9728, 256, 256, 256, 9728 ]
          - Exact: [ 256, 8976, 1, 9984, 256, 256, 256, 9984 ]
          - Exact: [ 257, 1024, 1, 4096, 257, 257, 257, 4096 ]
          - Exact: [ 3200, 1024, 1, 2048, 3200, 3200, 3200, 2048 ]
          - Exact: [ 32, 200, 1, 1, 32, 32, 32, 1 ]
          - Exact: [ 4096, 1024, 1, 1, 4096, 4096, 4096, 1 ]
          - Exact: [ 512, 1600, 1, 32, 512, 512, 512, 32 ]
          - Exact: [ 512, 1600, 1, 512, 512, 512, 512, 512 ]
          - Exact: [ 512, 200, 1, 1, 512, 512, 512, 1 ]
          - Exact: [ 512, 200, 1, 32, 512, 512, 512, 32 ]
          - Exact: [ 512, 215, 1, 2048, 512, 512, 512, 2048 ]
          - Exact: [ 512, 256, 1, 2048, 512, 512, 512, 2048 ]
          - Exact: [ 560, 1600, 1, 1024, 560, 560, 560, 1024 ]
          - Exact: [ 560, 200, 1, 1024, 560, 560, 560, 1024 ]
          - Exact: [ 64, 512, 1, 1, 64, 64, 64, 1 ]
          - Exact: [ 67, 512, 1, 2048, 67, 67, 67, 2048 ]
          - Exact: [ 74, 512, 1, 2048, 74, 74, 74, 2048 ]
          - Exact: [ 768, 215, 1, 2048, 768, 768, 768, 2048 ]
          - Exact: [ 768, 256, 1, 2048, 768, 768, 768, 2048 ]
          - Exact: [ 32, 33, 1600, 33, 32, 32, 32, 33 ]
          - Exact: [ 64, 3, 512, 3, 64, 64, 64, 3 ]
          - Exact: [ 64, 5, 512, 5, 64, 64, 64, 5 ]
          - Exact: [ 64, 9, 512, 9, 64, 64, 64, 9 ]

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        #- LoopTail: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [32, 32, 1, 2]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 2, 32 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
        - WorkGroupMapping: [8]
        - GlobalSplitU: [1]
        - DepthU: [8,16]
        - VectorWidth: [1]
        - GlobalReadVectorWidth: [-1,1,2,4]
        - SuppressNoLoadLoop: [True,False]
        - OptNoLoadLoop: [0,1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 100, 512, 1, 2048, 100, 100, 100, 2048 ]
          - Exact: [ 1024, 10240, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 10496, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 11008, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 11264, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 11520, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 1, 1, 1600, 1024, 1024, 1024, 1600 ]
          - Exact: [ 1024, 1, 1, 200, 1024, 1024, 1024, 200 ]
          - Exact: [ 1024, 12288, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 13312, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 13568, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 14336, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 14592, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 14848, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 15104, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 1600, 1, 1024, 1024, 1024, 1024, 1024 ]
          - Exact: [ 1024, 1600, 1, 1, 1024, 1024, 1024, 1 ]
          - Exact: [ 1024, 16128, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 17152, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 1792, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 18944, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 19712, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 19968, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 200, 1, 1, 1024, 1024, 1024, 1 ]
          - Exact: [ 1024, 20480, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 2048, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 20992, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 21504, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 22016, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 23552, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 2560, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 28672, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 3072, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 3328, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 33536, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 3840, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 40448, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 4096, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 4608, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 4864, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 5120, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 512, 1, 1024, 1024, 1024, 1024, 1024 ]
          - Exact: [ 1024, 512, 1, 1, 1024, 1024, 1024, 1 ]
          - Exact: [ 1024, 512, 1, 64, 1024, 1024, 1024, 64 ]
          - Exact: [ 1024, 5632, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 6144, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 6400, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 7168, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 7424, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 7680, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 7936, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 8192, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 8448, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 8704, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 8960, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 9728, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1024, 9984, 1, 256, 1024, 1024, 1024, 256 ]
          - Exact: [ 1, 200, 1, 1, 1, 1, 1, 1 ]
          - Exact: [ 1, 512, 1, 1, 1, 1, 1, 1 ]
          - Exact: [ 1600, 512, 1, 1024, 1600, 1600, 1600, 1024 ]
          - Exact: [ 2048, 1024, 1, 1, 2048, 2048, 2048, 1 ]
          - Exact: [ 2048, 1024, 1, 256, 2048, 2048, 2048, 256 ]
          - Exact: [ 2048, 1, 1, 512, 2048, 2048, 2048, 512 ]
          - Exact: [ 2048, 512, 1, 1, 2048, 2048, 2048, 1 ]
          - Exact: [ 2048, 512, 1, 2048, 2048, 2048, 2048, 2048 ]
          - Exact: [ 256, 1024, 1, 1, 256, 256, 256, 1 ]
          - Exact: [ 256, 8976, 1, 10240, 256, 256, 256, 10240 ]
          - Exact: [ 256, 8976, 1, 10496, 256, 256, 256, 10496 ]
          - Exact: [ 256, 8976, 1, 11008, 256, 256, 256, 11008 ]
          - Exact: [ 256, 8976, 1, 11520, 256, 256, 256, 11520 ]
          - Exact: [ 256, 8976, 1, 12288, 256, 256, 256, 12288 ]
          - Exact: [ 256, 8976, 1, 14336, 256, 256, 256, 14336 ]
          - Exact: [ 256, 8976, 1, 14848, 256, 256, 256, 14848 ]
          - Exact: [ 256, 8976, 1, 15104, 256, 256, 256, 15104 ]
          - Exact: [ 256, 8976, 1, 1536, 256, 256, 256, 1536 ]
          - Exact: [ 256, 8976, 1, 15872, 256, 256, 256, 15872 ]
          - Exact: [ 256, 8976, 1, 17152, 256, 256, 256, 17152 ]
          - Exact: [ 256, 8976, 1, 19712, 256, 256, 256, 19712 ]
          - Exact: [ 256, 8976, 1, 19968, 256, 256, 256, 19968 ]
          - Exact: [ 256, 8976, 1, 20480, 256, 256, 256, 20480 ]
          - Exact: [ 256, 8976, 1, 2048, 256, 256, 256, 2048 ]
          - Exact: [ 256, 8976, 1, 20992, 256, 256, 256, 20992 ]
          - Exact: [ 256, 8976, 1, 22016, 256, 256, 256, 22016 ]
          - Exact: [ 256, 8976, 1, 2304, 256, 256, 256, 2304 ]
          - Exact: [ 256, 8976, 1, 2560, 256, 256, 256, 2560 ]
          - Exact: [ 256, 8976, 1, 26112, 256, 256, 256, 26112 ]
          - Exact: [ 256, 8976, 1, 2816, 256, 256, 256, 2816 ]
          - Exact: [ 256, 8976, 1, 3072, 256, 256, 256, 3072 ]
          - Exact: [ 256, 8976, 1, 33536, 256, 256, 256, 33536 ]
          - Exact: [ 256, 8976, 1, 4352, 256, 256, 256, 4352 ]
          - Exact: [ 256, 8976, 1, 44505, 256, 256, 256, 44505 ]
          - Exact: [ 256, 8976, 1, 4864, 256, 256, 256, 4864 ]
          - Exact: [ 256, 8976, 1, 5376, 256, 256, 256, 5376 ]
          - Exact: [ 256, 8976, 1, 5632, 256, 256, 256, 5632 ]
          - Exact: [ 256, 8976, 1, 5888, 256, 256, 256, 5888 ]
          - Exact: [ 256, 8976, 1, 6144, 256, 256, 256, 6144 ]
          - Exact: [ 256, 8976, 1, 6656, 256, 256, 256, 6656 ]
          - Exact: [ 256, 8976, 1, 7168, 256, 256, 256, 7168 ]
          - Exact: [ 256, 8976, 1, 7424, 256, 256, 256, 7424 ]
          - Exact: [ 256, 8976, 1, 8192, 256, 256, 256, 8192 ]
          - Exact: [ 256, 8976, 1, 8448, 256, 256, 256, 8448 ]
          - Exact: [ 256, 8976, 1, 8960, 256, 256, 256, 8960 ]
          - Exact: [ 256, 8976, 1, 9472, 256, 256, 256, 9472 ]
          - Exact: [ 256, 8976, 1, 9728, 256, 256, 256, 9728 ]
          - Exact: [ 256, 8976, 1, 9984, 256, 256, 256, 9984 ]
          - Exact: [ 257, 1024, 1, 4096, 257, 257, 257, 4096 ]
          - Exact: [ 3200, 1024, 1, 2048, 3200, 3200, 3200, 2048 ]
          - Exact: [ 32, 200, 1, 1, 32, 32, 32, 1 ]
          - Exact: [ 4096, 1024, 1, 1, 4096, 4096, 4096, 1 ]
          - Exact: [ 512, 1600, 1, 32, 512, 512, 512, 32 ]
          - Exact: [ 512, 1600, 1, 512, 512, 512, 512, 512 ]
          - Exact: [ 512, 200, 1, 1, 512, 512, 512, 1 ]
          - Exact: [ 512, 200, 1, 32, 512, 512, 512, 32 ]
          - Exact: [ 512, 215, 1, 2048, 512, 512, 512, 2048 ]
          - Exact: [ 512, 256, 1, 2048, 512, 512, 512, 2048 ]
          - Exact: [ 560, 1600, 1, 1024, 560, 560, 560, 1024 ]
          - Exact: [ 560, 200, 1, 1024, 560, 560, 560, 1024 ]
          - Exact: [ 64, 512, 1, 1, 64, 64, 64, 1 ]
          - Exact: [ 67, 512, 1, 2048, 67, 67, 67, 2048 ]
          - Exact: [ 74, 512, 1, 2048, 74, 74, 74, 2048 ]
          - Exact: [ 768, 215, 1, 2048, 768, 768, 768, 2048 ]
          - Exact: [ 768, 256, 1, 2048, 768, 768, 768, 2048 ]
          - Exact: [ 32, 33, 1600, 33, 32, 32, 32, 33 ]
          - Exact: [ 64, 3, 512, 3, 64, 64, 64, 3 ]
          - Exact: [ 64, 5, 512, 5, 64, 64, 64, 5 ]
          - Exact: [ 64, 9, 512, 9, 64, 64, 64, 9 ]

########################################
LibraryLogic:
    ScheduleName: "arcturus"
    DeviceNames: ["Device 7380", "Device 7388", "Device 738c", "Device 7390"]
    ArchitectureName: "gfx908"
