GlobalParameters:
  MinimumRequiredVersion: 4.1.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 2
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: True
  SleepPercent: 200
  DataInitTypeBeta : 0

BenchmarkProblems:

  ########################################
  # NN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Source"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ -2 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [2], [64] ]

  ########################################
  # NT
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Source"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ -2 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [2], [64] ]

  ########################################
  # TN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Source"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ -2 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [2], [64] ]

  ########################################
  # TT
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Source"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ -2 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [2], [64] ]

LibraryLogic:
#   ScheduleName: "vega10"
#   DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "mi25"
#   DeviceNames: ["Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "r9nano"
#   DeviceNames: ["Device 7300"]
#   ArchitectureName: "gfx803"

    ScheduleName: "hip"
    DeviceNames: ["Device 0000"]
    ArchitectureName: "fallback"

LibraryClient:
