GlobalParameters:
  MinimumRequiredVersion: 4.4.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 1000
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: True
  SleepPercent: 200
  DataInitTypeBeta : 0

BenchmarkProblems:
  ########################################
  # NT - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
      ForkParameters:
        - PrefetchLocalRead: [True,False]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 6, 4 ]
          - [ 8, 4 ]
          - [ 6, 6 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
          - [ 16, 32, 1 ]
        - WorkGroupMapping: [8]
        - GlobalSplitU: [1]
        - DepthU: [ 8 ]
        - VectorWidth: [2]
        - FractionalLoad : [1]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
        - GlobalSplitU
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 16, 16, 1, 16 ]
          - Exact: [ 32, 32, 1, 32 ]
          - Exact: [ 64, 64, 1, 64 ]
          - Exact: [ 128, 128, 1, 128 ]
          - Exact: [ 256, 256, 1, 256 ]
          - Exact: [ 512, 512, 1, 512 ]
          - Exact: [ 1024, 1024, 1, 1024 ]
          - Exact: [ 2048, 2048, 1, 2048 ]
          - Exact: [ 4096, 4096, 1, 4096 ]
          - Exact: [ 6144, 6144, 1, 6144]
          - Exact: [ 8192, 8192, 1, 8192 ]
          - Exact: [ 10240, 10240, 1, 10240]
          - Exact: [ 12288, 12288, 1, 12288]
          - Exact: [ 14366, 14366, 1, 14366]
          - Exact: [ 16384, 16384, 1, 16384 ]
          - Exact: [ 18432, 18432, 1, 18432 ]
          - Exact: [ 20480, 20480, 1, 20480 ]
          - Exact: [ 22528, 22528, 1, 22528 ]
          - Exact: [ 24576, 24576, 1, 24576 ]
          - Exact: [ 26624, 26624, 1, 26624 ]

    - # BenchmarkProblemSizeGroup - 
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - ThreadTile:
          - [ 6, 6 ]
        - WorkGroup:
          - [ 32, 16, 1 ]
        - WorkGroupMapping: [8]
        - GlobalSplitU: [1]
        - DepthU: [ 8 ]
        - VectorWidth: [2]
        - FractionalLoad : [1]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
        - GlobalSplitU
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 16, 16, 1, 16 ]
          - Exact: [ 32, 32, 1, 32 ]
          - Exact: [ 64, 64, 1, 64 ]
          - Exact: [ 128, 128, 1, 128 ]
          - Exact: [ 256, 256, 1, 256 ]
          - Exact: [ 512, 512, 1, 512 ]
          - Exact: [ 1024, 1024, 1, 1024 ]
          - Exact: [ 2048, 2048, 1, 2048 ]
          - Exact: [ 4096, 4096, 1, 4096 ]
          - Exact: [ 6144, 6144, 1, 6144]
          - Exact: [ 8192, 8192, 1, 8192 ]
          - Exact: [ 10240, 10240, 1, 10240]
          - Exact: [ 12288, 12288, 1, 12288]
          - Exact: [ 14366, 14366, 1, 14366]
          - Exact: [ 16384, 16384, 1, 16384 ]
          - Exact: [ 18432, 18432, 1, 18432 ]
          - Exact: [ 20480, 20480, 1, 20480 ]
          - Exact: [ 22528, 22528, 1, 22528 ]
          - Exact: [ 24576, 24576, 1, 24576 ]
          - Exact: [ 26624, 26624, 1, 26624 ]

  ########################################
