# benchmark fastest kernels for the 5760 size
GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  KernelLanguage: gfx900
  CMakeBuildType: Release
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  DataInitTypeAB: 3
  DataInitTypeC: 3
  KernelTime: True

BenchmarkProblems:

  - # sgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: False

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [1023, 1, 1025], 0, [127,1,129] ]
        - LoopDoWhile: [False]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - WorkGroupMapping: [1, 8]
        - PrefetchLocalRead: [False, True]
        - PrefetchGlobalRead: [False, True]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8, 16]
        - VectorWidth: [2, 4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1023, 1, 1025], 0, [127,1,129] ]

  - # sgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: False

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [1023, 1, 1025], 0, [127,1,129] ]
        - LoopDoWhile: [False]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - WorkGroupMapping: [1, 8]
        - PrefetchLocalRead: [False, True]
        - PrefetchGlobalRead: [False, True]
        - ThreadTile:
          - [ 4, 4 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [ 8, 16,  1 ]
        - DepthU: [4, 8, 16]
        - VectorWidth: [2, 4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1023, 1, 1025], 0, [127,1,129] ]

  - # sgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: False

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [1023, 1, 1025], 0, [127,1,129] ]
        - LoopDoWhile: [False]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - WorkGroupMapping: [1, 8]
        - PrefetchLocalRead: [False, True]
        - PrefetchGlobalRead: [False, True]
        - ThreadTile:
          - [ 4, 4 ]
          - [ 4, 8 ]
        - WorkGroup:
          - [  8, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8, 16]
        - VectorWidth: [2, 4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1023, 1, 1025], 0, [127,1,129] ]

  - # sgemm TT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: False

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [1023, 1, 1025], 0, [127,1,129] ]
        - LoopDoWhile: [False]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - WorkGroupMapping: [-1, -8]
        - PrefetchLocalRead: [False, True]
        - PrefetchGlobalRead: [False, True]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8, 16,  1 ]
        - DepthU: [4, 8, 16]
        - VectorWidth: [2, 4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1023, 1, 1025], 0, [127,1,129] ]

LibraryLogic:

LibraryClient:
