GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: -1
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True

BenchmarkProblems:
  - # 4-D batched sgemm NN
    - # ProblemType
      OperationType: TensorContraction
      DataType: s
      UseBeta: True
      NumIndicesC: 3
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
      ForkParameters:
        - ThreadTile:
          - [ 4, 8 ]
          - [ 4, 4 ]
          - [ 2, 4 ]
        - WorkGroup:
          - [  8, 16,  1 ]
          - [ 16, 16,  1 ]
        - DepthU: [4, 8]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,128], [127,1,128], [2, 1, 3], [63,1,65] ]

  - # 4-D with 2-D summation
    - # ProblemType
      OperationType: TensorContraction
      DataType: s
      UseBeta: True
      NumIndicesC: 2
      IndexAssignmentsA: [2, 0, 3]
      IndexAssignmentsB: [2, 1, 3]
      # C[ij] = Sum[kl] A[kil] * B[kjl]
      # Free Indices: [i, j]
      # Batch Indices:
      # Sum Indices:   k, l

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
      ForkParameters:
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - ThreadTile:
          - [ 4, 4 ]
          - [ 2, 4 ]
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  4 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [63,1,65], [63,1,65], [2,1,3], [15,1,17] ]

  - # 5-D "gemm" with 3-D summation
    - # ProblemType
      OperationType: TensorContraction
      DataType: s
      UseBeta: True
      NumIndicesC: 2
      IndexAssignmentsA: [4, 3, 0, 2]
      IndexAssignmentsB: [4, 3, 2, 1]
      # C[ij] = Sum[klm] A[mlik] * B[mlkj]
      # Free Indices: [i, j]
      # Batch Indices:
      # Sum Indices: k, l, m

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
      ForkParameters:
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 4, 4 ]
          - [ 2, 2 ]
        - WorkGroup:
          - [  4,  8,  2 ]
          - [  8,  8,  1 ]
          - [ 16, 16,  1 ]
        - DepthU: [4, 8]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [63,1,65], [63,1,65], [2,1,3], [2,1,3], [15,1,17] ]

  - # 6-D Image Convolution
    - # ProblemType
      OperationType: TensorContraction
      DataType: s
      UseBeta: True
      NumIndicesC: 3
      IndexAssignmentsA: [5, 4, 0, 1, 3]
      IndexAssignmentsB: [5, 4, 1, 3, 2]
      # C[ijk] = Sum[lmn] A[nmijl] * B[nmjlk]
      # Free Indices: [i, k]
      # Batch Indices: j
      # Sum Indices: l, m, n

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
      ForkParameters:
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 4, 4 ]
          - [ 2, 2 ]
        - WorkGroup:
          - [  4,  8,  2 ]
          - [  8,  8,  1 ]
          - [ 16, 16,  1 ]
        - DepthU: [4, 8]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [63,1,65], [2,1,3], [63,1,65], [2,1,3], [2,1,3], [15,1,17] ]

LibraryLogic:

LibraryClient:
