# benchmark assembly and source kernels
GlobalParameters:
  MinimumRequiredVersion: 3.2.0
  CMakeBuildType: Release
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  NumElementsToValidate: -1
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  DataInitTypeAB: 3
  DataInitTypeC: 3
  KernelTime: True

BenchmarkProblems:

  - # sgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 3, 5 ]
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 32,  4,  1 ]
          - [  8,  8,  1 ]
          - [  4,  8,  4 ]
        - DepthU: [-3]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - KernelLanguage: ["Source", "Assembly"]
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 3, 3 ]
          - [ 4, 4 ]
          - [ 5, 5 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
          - [  4,  4,  4 ]
        - DepthU: [-1]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

  - # sgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 3, 5 ]
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8, 16,  1 ]
          - [  2,  8,  8 ]
        - DepthU: [-3]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - KernelLanguage: ["Source", "Assembly"]
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 3, 3 ]
          - [ 4, 4 ]
          - [ 5, 5 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [ 16,  8,  1 ]
          - [ 16,  2,  8 ]
        - DepthU: [-1]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

  - # sgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 3, 5 ]
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [ 32,  4,  1 ]
        - DepthU: [-4]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - KernelLanguage: ["Source", "Assembly"]
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 3, 3 ]
          - [ 4, 4 ]
          - [ 5, 5 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [-1]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

  - # sgemm TT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 3, 5 ]
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [-3]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - KernelLanguage: ["Source", "Assembly"]
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 3, 3 ]
          - [ 4, 4 ]
          - [ 5, 5 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [-1]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

LibraryLogic:
  SolutionImportanceMin: 0
LibraryClient:
