GlobalParameters:
  MinimumRequiredVersion: 4.0.1
  ForceRedoBenchmarkProblems: True
  PrintLevel: 1
  CMakeBuildType: Release
  NumElementsToValidate: 1000
  ValidationMaxToPrint: 4 
  ValidationPrintValids: False
  DataInitTypeA: 3           # 0=0, 1=1, 2=serial, 3=rand, 4=NaN
  DataInitTypeB: 3           # 0=0, 1=1, 2=serial, 3=rand, 4=NaN
  DataInitTypeC : 3            # 0=0, 1=1, 2=serial, 3=rand, 4=NaN

BenchmarkProblems:
  ########################################
  # NT - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Source"]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - GlobalSplitU: [1, 3, 5]
        - PersistentKernel: [0]
        - ThreadTile:
          - [ 8, 8 ]
        - WorkGroup:
          - [ 32,  4,  1 ]
          - [ 8, 8, 1 ]
        - WorkGroupMapping: [1,2,8,-1,-2,-8]
        - DepthU: [ 8 ]
        - GlobalReadVectorWidth: [2]
        - VectorWidth: [2]
      BenchmarkFinalParameters:
        - ProblemSizes:
          #- Exact: [ 1, 1, 1, 1]
          - Range: [ [256,128,1024], [512], [1], [64] ]
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]


    - # ProblemType - Half Precision test
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Source"]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - GlobalSplitU: [1, 3, 5]
        - PersistentKernel: [1]
        - ThreadTile:
          - [ 8, 8 ]
        - WorkGroup:
          - [ 32,  4,  1 ]
          - [ 8, 8, 1 ]
        - WorkGroupMapping: [1,2,8,-1,-2,-8]
        - DepthU: [ 8 ]
        - GlobalReadVectorWidth: [2]
        - VectorWidth: [2]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 2, 2, 2, 2]
          - Range: [ [256,128,1024], [512], [1], [64] ]
          - Range: [ [256,128,1024], [256], [1], [16] ]
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

  ########################################


