GlobalParameters:
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  PrintSolutionRejectionReason: False
  MinimumRequiredVersion: 4.1.1
  NumElementsToValidate: -1
  ValidationMaxToPrint: 4
  DataInitTypeAB: 1
  DataInitTypeC: 1

BenchmarkProblems:

    ############################################################################
    # NN
    ############################################################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: False
      Batched: True

    - # Tile Sizes
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - MacroTileShapeMax: [64]
      ForkParameters:
        - ThreadTile:
          - [8, 8]
          - [7, 4]
          - [3, 5]
          - [2, 6]
          - [1, 1]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  2, 16 ]
          - [ 16, 12,  1 ]
        - DepthU: [ 2, 16, 64 ]
        - GlobalSplitU: [1, 4]
        - VectorWidth: [1]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [   1, 1, 1, 1 ]
          - Range: [ [127, 1, 129], [127, 1, 129], [1, 2], [63, 1, 65] ]


    - # Non-Tile Sizes
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroup: [ [8, 8, 2 ] ]
        - ThreadTile: [ [4, 8] ]
        - DepthU: [ 16 ]
      ForkParameters:
        - GlobalReadCoalesceGroupA: [False, True]
        - GlobalReadCoalesceGroupB: [False, True]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - VectorWidth: [1]
        - GlobalSplitU: [1, 4]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127, 1, 129], [127, 1, 129], [1], [63, 1, 65] ]

    - # Branches
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - DepthU: [ 16 ]
      ForkParameters:
        - ThreadTile:
          - [8, 8]
          - [2, 8]
        - WorkGroup:
          - [  8,  4, 4 ]
          - [ 16, 16, 1 ]
        - VectorWidth: [1]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [8, 32, 0, 75], [8, 32, 0, 75], [3], [63, 1, 64] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - KernelLanguage: ["Source", "Assembly"]
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 3, 3 ]
          - [ 4, 4 ]
          - [ 5, 5 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
          - [  4,  4,  4 ]
        - DepthU: [-1]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

    ############################################################################
    # NT
    ############################################################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: False

    - # Tile Sizes
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - MacroTileShapeMax: [64]
      ForkParameters:
        - ThreadTile:
          - [8, 8]
          - [7, 4]
          - [3, 5]
          - [2, 6]
          - [1, 1]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  2, 16 ]
          - [ 16, 12,  1 ]
        - DepthU: [ 2, 16, 64 ]
        - GlobalSplitU: [1, 4]
        - VectorWidth: [1]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [   1,   1,   1 ]
          - Range: [ [127, 1, 129], [127, 1, 129], [63, 1, 65] ]


    - # Non-Tile Sizes
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroup: [ [8, 8, 2 ] ]
        - ThreadTile: [ [4, 8] ]
        - DepthU: [ 16 ]
      ForkParameters:
        - GlobalReadCoalesceGroupA: [False, True]
        - GlobalReadCoalesceGroupB: [False, True]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - VectorWidth: [1]
        - GlobalSplitU: [1, 4]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127, 1, 129], [127, 1, 129], [63, 1, 65] ]

    - # Branches
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - DepthU: [ 16 ]
      ForkParameters:
        - ThreadTile:
          - [8, 8]
          - [2, 8]
        - WorkGroup:
          - [  8,  4, 4 ]
          - [ 16, 16, 1 ]
        - VectorWidth: [1]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]


    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - KernelLanguage: ["Source", "Assembly"]
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 3, 3 ]
          - [ 4, 4 ]
          - [ 5, 5 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [ 16,  8,  1 ]
          - [ 16,  2,  8 ]
        - DepthU: [-1]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]


    ############################################################################
    # TN
    ############################################################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True

    - # Tile Sizes
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - MacroTileShapeMax: [64]
      ForkParameters:
        - ThreadTile:
          - [8, 8]
          - [7, 4]
          - [3, 5]
          - [2, 6]
          - [1, 1]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  2, 16 ]
          - [ 16, 12,  1 ]
        - DepthU: [ 2, 16, 64 ]
        - GlobalSplitU: [1, 4]
        - VectorWidth: [1]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [   1,   1,   1 ]
          - Range: [ [127, 1, 129], [127, 1, 129], [63, 1, 65] ]


    - # Non-Tile Sizes
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroup: [ [8, 8, 2 ] ]
        - ThreadTile: [ [4, 8] ]
        - DepthU: [ 16 ]
      ForkParameters:
        - GlobalReadCoalesceGroupA: [False, True]
        - GlobalReadCoalesceGroupB: [False, True]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - VectorWidth: [1]
        - GlobalSplitU: [1, 4]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127, 1, 129], [127, 1, 129], [63, 1, 65] ]

    - # Branches
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - DepthU: [ 16 ]
      ForkParameters:
        - ThreadTile:
          - [8, 8]
          - [2, 8]
        - WorkGroup:
          - [  8,  4, 4 ]
          - [ 16, 16, 1 ]
        - VectorWidth: [1]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - KernelLanguage: ["Source", "Assembly"]
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 3, 3 ]
          - [ 4, 4 ]
          - [ 5, 5 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [-1]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]


    ############################################################################
    # TT
    ############################################################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: False

    - # Tile Sizes
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - MacroTileShapeMax: [64]
      ForkParameters:
        - ThreadTile:
          - [8, 8]
          - [7, 4]
          - [3, 5]
          - [2, 6]
          - [1, 1]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  2, 16 ]
          - [ 16, 12,  1 ]
        - DepthU: [ 2, 16, 64 ]
        - GlobalSplitU: [1, 4]
        - VectorWidth: [1]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [   1,   1,   1 ]
          - Range: [ [127, 1, 129], [127, 1, 129], [63, 1, 65] ]


    - # Non-Tile Sizes
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroup: [ [8, 8, 2 ] ]
        - ThreadTile: [ [4, 8] ]
        - DepthU: [ 16 ]
      ForkParameters:
        - GlobalReadCoalesceGroupA: [False, True]
        - GlobalReadCoalesceGroupB: [False, True]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - VectorWidth: [1]
        - GlobalSplitU: [1, 4]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127, 1, 129], [127, 1, 129], [63, 1, 65] ]

    - # Branches
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - DepthU: [ 16 ]
      ForkParameters:
        - ThreadTile:
          - [8, 8]
          - [2, 8]
        - WorkGroup:
          - [  8,  4, 4 ]
          - [ 16, 16, 1 ]
        - VectorWidth: [1]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - KernelLanguage: ["Source", "Assembly"]
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 3, 3 ]
          - [ 4, 4 ]
          - [ 5, 5 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [-1]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

LibraryLogic:
    ScheduleName: "vega10"
    DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860"]
    ArchitectureName: "gfx900"

#   ScheduleName: "mi25"
#   DeviceNames: ["Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "r9nano"
#   DeviceNames: ["Device 7300"]
#   ArchitectureName: "gfx803"

#   ScheduleName: "hip"
#   DeviceNames: ["Device 0000"]
#   ArchitectureName: "fallback"

LibraryClient:
