GlobalParameters:
  MinimumRequiredVersion: 4.0.2
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: -1
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True

BenchmarkProblems:
  - # 7-D batched Image Convolution
    - # ProblemType
      OperationType: TensorContraction
      DataType: s
      UseBeta: True
      NumIndicesC: 4
      IndexAssignmentsA: [6, 5, 0, 1, 4, 3]
      IndexAssignmentsB: [6, 5, 1, 4, 2, 3]
      # C[ijkl] = Sum[mno] A[onijml] * B[onjmkl]
      # Free Indices: [i, k]
      # Batch Indices: j, l
      # Sum Indices: m, n, o

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
      ForkParameters:
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 4, 4 ]
          - [ 2, 2 ]
        - WorkGroup:
          - [  4,  8,  2 ]
          - [  8,  8,  1 ]
          - [ 16, 16,  1 ]
        - DepthU: [4, 8]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [63,1,65], [2,1,3], [63,1,65], [2,1,3], [2,1,3], [2,1,3], [15,1,17] ]

LibraryLogic:
    ScheduleName: "vega10"
    DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860"]
    ArchitectureName: "gfx900"

#   ScheduleName: "mi25"
#   DeviceNames: ["Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "r9nano"
#   DeviceNames: ["Device 7300"]
#   ArchitectureName: "gfx803"

#   ScheduleName: "hip"
#   DeviceNames: ["Device 0000"]
#   ArchitectureName: "fallback"

LibraryClient:
