          - Exact: [ 1760 , 32 , 1, 1760 ]
          - Exact: [ 1760 , 64 , 1, 1760 ]
          - Exact: [ 1760 , 128 , 1, 1760 ]
          - Exact: [ 2048 , 16 , 1, 2048 ]
          - Exact: [ 2048 , 32 , 1, 2048 ]
          - Exact: [ 2048 , 64 , 1, 2048 ]
          - Exact: [ 2048 , 128 , 1, 2048 ]
          - Exact: [ 2560 , 16 , 1, 2560 ]
          - Exact: [ 2560 , 32 , 1, 2560 ]
          - Exact: [ 2560 , 64 , 1, 2560 ]
          - Exact: [ 2560 , 128 , 1, 2560 ]
          - Exact: [ 4096 , 16 , 1, 4096 ]
          - Exact: [ 4096 , 32 , 1, 4096 ]
          - Exact: [ 4096 , 64 , 1, 4096 ]
          - Exact: [ 4096 , 128 , 1, 4096 ]
          - Exact: [ 7680 , 16 , 1, 2560 ]
          - Exact: [ 7680 , 32 , 1, 2560 ]
          - Exact: [ 7680 , 64 , 1, 2560 ]
          - Exact: [ 7680 , 128 , 1, 2560 ]
          - Exact: [ 3072 , 16 , 1, 1024 ]
          - Exact: [ 3072 , 32 , 1, 1024 ]
          - Exact: [ 3072 , 64 , 1, 1024 ]
          - Exact: [ 3072 , 128 , 1, 1024 ]
          - Exact: [ 512 , 8 , 1, 500000 ]
          - Exact: [ 1024 , 8 , 1, 500000 ]
          - Exact: [ 512 , 16 , 1, 500000 ]
          - Exact: [ 1024 , 16 , 1, 500000 ]
          - Exact: [ 6144 , 16 , 1, 2048 ]
          - Exact: [ 4608 , 16 , 1, 1536 ]
          - Exact: [ 8448 , 16 , 1, 2816 ]
          - Exact: [ 6144 , 32 , 1, 2048 ]
          - Exact: [ 4608 , 32 , 1, 1536 ]
          - Exact: [ 8448 , 32 , 1, 2816 ]
          - Exact: [ 512 , 16 , 1, 512 ]
          - Exact: [ 1024 , 16 , 1, 512 ]
          - Exact: [ 512 , 32 , 1, 512 ]
          - Exact: [ 1024 , 32 , 1, 512 ]
