          # DeepBench batch>1 conv sizes 
          - Exact: [784, 64, 16, 192]
          - Exact: [196, 192, 16, 512]
          - Exact: [49, 256, 16, 832]
          - Exact: [196, 256, 8, 256]
          - Exact: [49, 512, 8, 512]
          - Exact: [196, 256, 16, 256]
          - Exact: [49, 512, 16, 512]
          - Exact: [12544, 64, 8, 64]
          - Exact: [3136, 256, 8, 64]
          - Exact: [3136, 64, 8, 256]
          - Exact: [784, 512, 8, 128]
          - Exact: [784, 128, 8, 512]
          - Exact: [196, 1024, 8, 256]
          - Exact: [196, 256, 8, 1024]
          - Exact: [196, 1024, 8, 256]
          - Exact: [49, 2048, 8, 512]
          - Exact: [49, 512, 8, 2048]
          - Exact: [12544, 64, 16, 64]
          - Exact: [3136, 256, 16, 64]
          - Exact: [3136, 64, 16, 256]
          - Exact: [784, 512, 16, 128]
          - Exact: [784, 128, 16, 512]
          - Exact: [196, 1024, 16, 256]
          - Exact: [196, 256, 16, 1024]
          - Exact: [196, 1024, 16, 256]
          - Exact: [49, 2048, 16, 512]
          - Exact: [49, 512, 16, 2048]

