  ########################################
  # Explore large number of ~10K half solutions
  ########################################
    - # NN workloads
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - FractionalLoad: [1]
        - PrefetchGlobalRead: [ False, True ]
        - PrefetchLocalRead: [ False, True]
        - ThreadTile:
          - [ 4, 4 ]
          - [ 8, 4 ]
          - [ 8, 8 ]
          - [ 16, 8 ]
          - [ 8, 16 ]
          - [ 16, 16 ]
        - WorkGroup:
          #- [ 16, 8, 2 ]  LSU broken for Half?
          #- [ 16, 4, 4 ]
          - [ 16,  8, 1 ]
          - [ 8, 32, 1 ]
          - [ 16, 16, 1 ]
          - [ 32,  8, 1 ]
          #- GlobalSplitU: [1,3,5]
        - GlobalSplitU: [1]
        - WorkGroupMapping: [1,8,64]
        - DepthU: [ 8,16,32 ]
        - VectorWidth: [2,4,8]
        - GlobalReadVectorWidth: [1,8]
        - LdsPadB: [0, -1 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:

