          - Exact: [ 1760 , 7133 , 1, 1760 ]
          - Exact: [ 2048 , 7133 , 1, 2048 ]
          - Exact: [ 2560 , 7133 , 1, 2560 ]
          - Exact: [ 4096 , 7133 , 1, 4096 ]
          - Exact: [ 3072 , 7435 , 1, 1024 ]
          - Exact: [ 7680 , 5481 , 1, 2560 ]
